services:
  test-data:
    build:
      context: ./
      dockerfile: Dockerfile
      target: test-data-download-stage
    command: [ "/bin/bash", "-c", "set -eou pipefail; cp --recursive /data/. /volume/mount/" ]
    image: benchmarking:test-data-download-stage
    volumes:
      - benchmarking-data:/volume/mount

  kalibr:
    build:
      context: thirdparty/kalibr
      dockerfile: Dockerfile_ros1_20_04
    depends_on:
      test-data:
        condition: service_completed_successfully
    entrypoint: /temporary/scripts/kalibr_entrypoint.sh
    image: kalibr:latest
    volumes:
      - benchmarking-data:/data
      - ./scripts/kalibr_entrypoint.sh:/temporary/scripts/kalibr_entrypoint.sh:ro
      - ./config:/temporary/config:ro

  python-tooling-image:
    build:
      context: ./
      dockerfile: Dockerfile
      target: python-tooling-stage
    image: benchmarking:python-tooling-stage

  parse-kalibr:
    depends_on:
      kalibr:
        condition: service_completed_successfully
      python-tooling-image:
        condition: service_completed_successfully
    image: benchmarking:python-tooling-stage
    # NOTE(Jack): This line here is important because it writes the parsed output directly to the host and not a docker
    # volume! If this is a long term strategy I am not 100% sure.
    entrypoint: ["python3", "/python_tooling/parse_kalibr.py", "/data/kalibr", "/temporary/output/parsed_kalibr_result.csv"]
    volumes:
      - benchmarking-data:/data
      - ./:/temporary/output

  build-results-page:
    depends_on:
      parse-kalibr:
        condition: service_completed_successfully
      python-tooling-image:
        condition: service_completed_successfully
    image: benchmarking:python-tooling-stage
    entrypoint: ["python3", "/python_tooling/build_html_webpage.py", "/temporary/output/index.html", "--results", "kalibr", "/temporary/output/parsed_kalibr_result.csv"]
    volumes:
      - ./:/temporary/output

volumes:
  benchmarking-data:
    name: benchmarking-data