services:
  assemble-test-data:
    build:
      context: ./
      dockerfile: Dockerfile
      target: test-data-download-stage
    entrypoint: [ "/bin/bash",
                  "-c",
                  "set -eoux pipefail;
                   cp --recursive /data/. ${BENCHMARKING_DATA_INPUT_DIR}/;
                   cp --recursive /mount/reprojection_dbs ${BENCHMARKING_DATA_INPUT_DIR}/" ]
    image: benchmarking:test-data-download-stage
    volumes:
      - benchmarking-data-input:${BENCHMARKING_DATA_INPUT_DIR}
      - ./reprojection_dbs/:/mount/reprojection_dbs/:ro

  python-tooling-image:
    build:
      context: ./
      dockerfile: Dockerfile
      target: python-tooling-stage
    image: benchmarking:python-tooling-stage

  process-reprojection-dbs:
    depends_on:
      assemble-test-data:
        condition: service_completed_successfully
      python-tooling-image:
        condition: service_completed_successfully
    image: benchmarking:python-tooling-stage
    entrypoint: [ "python3", "/python_tooling/process_reprojection_dbs.py", "${BENCHMARKING_DATA_INPUT_DIR}/reprojection_dbs", "/mount/config/reprojection/cache_keys.csv" ]
    volumes:
      - benchmarking-data-input:${BENCHMARKING_DATA_INPUT_DIR}
      - ./config/reprojection/cache_keys.csv:/mount/config/reprojection/cache_keys.csv

  kalibr:
    build:
      context: thirdparty/kalibr
      dockerfile: Dockerfile_ros1_20_04
    depends_on:
      assemble-test-data:
        condition: service_completed_successfully
    entrypoint: /mount/scripts/kalibr_entrypoint.sh
    environment:
      - BENCHMARKING_DATA_INPUT_DIR
      - BENCHMARKING_RESULTS_DIR
      - DATASET_SPECIFICATION_JSON
    image: kalibr:latest
    volumes:
      # NOTE(Jack): I would like to mount this volume as readonly but Kalibr writes the results to the data directory by
      # default so we need it to be read/write.
      - benchmarking-data-input:${BENCHMARKING_DATA_INPUT_DIR}
      - benchmarking-results:${BENCHMARKING_RESULTS_DIR}
      - ./config:/mount/config:ro
      - ./scripts/kalibr_entrypoint.sh:/mount/scripts/kalibr_entrypoint.sh:ro

  reprojection:
    build:
      args:
        BASE_IMAGE: "ubuntu:20.04@sha256:8feb4d8ca5354def3d8fce243717141ce31e2c428701f6682bd2fafe15388214"
      context: thirdparty/reprojection/
      dockerfile: building/Dockerfile
      target: ros1-app-stage
    depends_on:
      process-reprojection-dbs:
        condition: service_completed_successfully
    entrypoint: /mount/scripts/reprojection_entrypoint.sh
    environment:
      - BENCHMARKING_DATA_INPUT_DIR
      - BENCHMARKING_RESULTS_DIR
      - DATASET_SPECIFICATION_JSON
    image: reprojection:ros1-app
    volumes:
      # NOTE(Jack): We edit the databases so this cannot be a readonly mount
      - benchmarking-data-input:${BENCHMARKING_DATA_INPUT_DIR}
      - benchmarking-results:${BENCHMARKING_RESULTS_DIR}
      - ./config:/mount/config:ro
      - ./scripts/reprojection_entrypoint.sh:/mount/scripts/reprojection_entrypoint.sh:ro

  parse-kalibr:
    depends_on:
      kalibr:
        condition: service_completed_successfully
      python-tooling-image:
        condition: service_completed_successfully
    image: benchmarking:python-tooling-stage
    entrypoint: ["python3", "/python_tooling/parse_kalibr.py", "${BENCHMARKING_RESULTS_DIR}/kalibr", "${BENCHMARKING_RESULTS_DIR}/parsed/parsed_kalibr_result.csv"]
    volumes:
      - benchmarking-results:${BENCHMARKING_RESULTS_DIR}

  parse-reprojection:
    depends_on:
      reprojection:
        condition: service_completed_successfully
      python-tooling-image:
        condition: service_completed_successfully
    image: benchmarking:python-tooling-stage
    entrypoint: ["python3", "/python_tooling/parse_reprojection.py", "${BENCHMARKING_RESULTS_DIR}/reprojection", "${BENCHMARKING_RESULTS_DIR}/parsed/parsed_reprojection_result.csv"]
    volumes:
      - benchmarking-results:${BENCHMARKING_RESULTS_DIR}

  build-results-page:
    depends_on:
      parse-kalibr:
        condition: service_completed_successfully
      parse-reprojection:
        condition: service_completed_successfully
      python-tooling-image:
        condition: service_completed_successfully
    image: benchmarking:python-tooling-stage
    entrypoint: ["python3", "/python_tooling/build_html_webpage.py", "/mount/index.html", "--results", "kalibr", "${BENCHMARKING_RESULTS_DIR}/parsed/parsed_kalibr_result.csv", "--results", "reprojection", "${BENCHMARKING_RESULTS_DIR}/parsed/parsed_reprojection_result.csv"]
    volumes:
      - ./:/mount
      - benchmarking-results:${BENCHMARKING_RESULTS_DIR}

volumes:
  benchmarking-data-input:
    name: benchmarking-data-input
  benchmarking-results:
    name: benchmarking-results
