name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

# https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # TODO(Jack): We should think about using gha "cache" as possible way to speed up the data handling here. It is just
  # not needed to uploaded the artifact everytime and download it again. If we can just upload it once and store it in
  # the cache that would make a lot of sense.
  test-data-download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Test data cache
        id: test-data-cache
        uses: actions/cache@v6
        # TODO(Jack): Can we also include a hash of the test data download docker image? I see a world where just
        # hashing the script here could cause us problems one day. For example what if we changed the base image, or
        # adding commands in the docker image after the download script it called?
        # TODO(Jack): Should we just hash the entire dockerfile here? Yes that would cause false positives but
        # eliminate the possibility of false negatives.
        with:
          path: ${{ runner.temp }}/test_data
          key: test-data-${{ hashFiles('scripts/download_test_data.sh') }}-cache-key
      - name: Download TUM test data
        if: steps.test-data-cache.outputs.cache-hit != 'true'
        uses: ./.github/actions/docker-build
        with:
          cache_scope: test-data-download
          context: .
          load: true
          tag: benchmarking:test-data-download-stage
          target: test-data-download-stage
      - name: Copy test data from Docker volume to host
        if: steps.test-data-cache.outputs.cache-hit != 'true'
        run: |
          set -eoux pipefail
          
          mount_dir="test_data"
          host_dir="${RUNNER_TEMP}/${mount_dir}"
          
          mkdir --parents "${host_dir}"
 
          docker run \
            --mount "type=bind,source=${host_dir},target=/mount/${mount_dir}" \
            --rm \
            benchmarking:test-data-download-stage \
              cp --debug --recursive /data/. "/mount/${mount_dir}"
          
          ls "${host_dir}"

  kalibr-pipeline:
    needs: test-data-download
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Build the Kalibr image
        uses: ./.github/actions/docker-build
        with:
          cache_scope: kalibr-build
          context: thirdparty/kalibr
          file: thirdparty/kalibr/Dockerfile_ros1_20_04
          load: true
          tag: kalibr
      # TOOD(Jack): Because will will likely use this exact same image for the reprojection pipeline, it would be nice
      # to only build it once and use the same image in both places just with the entrypoint overriden.
      - name: Build the python tooling image
        uses: ./.github/actions/docker-build
        with:
          cache_scope: python-tooling
          context: .
          load: true
          tag: benchmarking:python-tooling-stage
          target: python-tooling-stage
      - name: Restore test data cache
        uses: actions/cache/restore@v6
        with:
          path: ${{ runner.temp }}/test_data
          key: test-data-${{ hashFiles('scripts/download_test_data.sh') }}-cache-key
          fail-on-cache-miss: true
      # TODO(Jack): We will likely have this exact same step in the reprojection pipeline, should we make this into a
      # reusable action code block then?
      - name: Load test data into docker volume
        run: |
          set -eou pipefail

          docker volume create benchmarking-data-input
          
          # TODO(Jack): Can we not define these as environmental variables?
          mount_dir="test_data"
          host_dir="${RUNNER_TEMP}/${mount_dir}"

          docker run \
            --mount "type=volume,source=benchmarking-data-input,target=/volume/mount" \
            --mount "type=bind,source=${host_dir},target=/mount/${mount_dir},readonly" \
            --rm \
            ubuntu:24.04 \
              cp --debug --recursive ${host_dir}/. /volume/mount

      - name: Run experiment
        run: |
          set -eou pipefail
          
          # NOTE(Jack): We do not need to build anything here or run the test data portion of the compose file because 
          # both test data and kalibr build stages are built and cached in the pipeline before. We split this up in the 
          # gha CI because if we just ran it all here we would not be able to cache anything using the gha tooling. 
          docker compose --file compose.benchmark.yaml \
            run --no-deps --rm kalibr
          
          docker compose --file compose.benchmark.yaml \
            run --no-deps --rm parse-kalibr

      - name: Upload parsed Kalibr results
        uses: actions/upload-artifact@v7
        with:
          name: parsed-kalibr-result
          path: ${{ github.workspace }}/parsed_kalibr_result.csv
          if-no-files-found: error

  # NOTE(Jack): We split building the webpage and its deployment because we should build it everytime, regardless if we
  # want to deploy it or not. If we had a nice way to deploy on non-main branches that would be great, but it does not
  # exist. By building the webpage here we at least give the user the opportunity to download the website folder and run
  # it locally before merging to master - not even close to perfect, but better than nothing!
  build-results-webpage:
    needs: kalibr-pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # TODO(Jack): This is copy and pasted from the kalibr stage! Is there not a better way to do this?
      # TODO(Jack): Does the cache get shared across jobs? I think it does, regardless we need a more official way...
      - name: Build the python tooling image
        uses: ./.github/actions/docker-build
        with:
          cache_scope: python-tooling
          context: .
          load: true
          tag: benchmarking:python-tooling-stage
          target: python-tooling-stage
      - name: Download parsed Kalibr results
        uses: actions/download-artifact@v8
        with:
          name: parsed-kalibr-result
          path: ${{ github.workspace }}
      - name: Create result webpage
        run: |
          set -eou pipefail
          
          test -f "${GITHUB_WORKSPACE}/parsed_kalibr_result.csv"
          
          # TODO(Jack): Should we pass the output directory here?
          docker compose --file compose.benchmark.yaml \
            run --no-deps --rm build-results-page

      - name: Upload result webpage
        uses: actions/upload-artifact@v7
        with:
          name: result-webpage
          path: ${{ github.workspace }}/index.html
          if-no-files-found: error

  deploy-results-webpage:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-results-webpage
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - name: Download built webpage
        uses: actions/download-artifact@v8
        with:
          name: result-webpage
          path: ${{ github.workspace }}/website
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/website
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5