name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

# https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  test-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Download TUM test data
        uses: ./.github/actions/docker-build
        with:
          cache_scope: test-data-download
          context: .
          load: true
          tag: reprojection:test-data-download-stage
          target: test-data-download-stage
      - name: Pack test data into zip file
        run: |
          set -eoux pipefail
    
          mkdir --parents "${RUNNER_TEMP}/artifacts"
          
          docker run \
            --rm \
            --mount "type=bind,source=${RUNNER_TEMP}/artifacts,target=/artifacts" \
            --mount "type=volume,source=benchmarking-data,target=/data,readonly" \
            reprojection:test-data-download-stage \
              tar \
                --create \
                --directory=/data \
                --file=/artifacts/benchmarking-data.tar.gz \
                --gzip \
                --verbose \
                .

      - name: Upload zipped test data
        uses: actions/upload-artifact@v7
        with:
          name: benchmarking-data
          path: ${{ runner.temp }}/artifacts/benchmarking-data.tar.gz
          if-no-files-found: error
  kalibr-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Build the Kalibr image
        uses: ./.github/actions/docker-build
        with:
          cache_scope: kalibr-build
          context: thirdparty/kalibr
          file: thirdparty/kalibr/Dockerfile_ros1_20_04
          load: true
          tag: kalibr